<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-02-24 23:13

$extensionPath = t3lib_extMgm::extPath('damlightbox');
return array(
	'tx_damlightbox_dblist' => $extensionPath . 'hooks/class.tx_damlightbox_dblist.php',
	'tx_damlightbox_div' => $extensionPath . 'pi1/class.tx_damlightbox_div.php',
	'tx_damlightbox_lightbox' => $extensionPath . 'pi1/class.tx_damlightbox_lightbox.php',
	'tx_damlightbox_module1' => $extensionPath . 'mod1/index.php',
	'tx_damlightbox_pages' => $extensionPath . 'pi1/class.tx_damlightbox_pages.php',
	'tx_damlightbox_pi1' => $extensionPath . 'pi1/class.tx_damlightbox_pi1.php',
	'tx_damlightbox_realurl' => $extensionPath . 'pi1/class.tx_damlightbox_realurl.php',
	'tx_damlightbox_tceform' => $extensionPath . 'hooks/class.tx_damlightbox_tceform.php',
	'tx_damlightbox_tcemain' => $extensionPath . 'hooks/class.tx_damlightbox_tcemain.php',
	'tx_damlightbox_ttaddress' => $extensionPath . 'pi1/class.tx_damlightbox_ttaddress.php',
	'tx_damlightbox_ttnews' => $extensionPath . 'pi1/class.tx_damlightbox_ttnews.php',
	't3lib_localRecordListGetTableHook' => PATH_t3lib . 'interfaces/interface.t3lib_localrecordlistgettablehook.php',
	't3lib_flexformtools' => PATH_t3lib . 'class.t3lib_flexformtools.php',
	't3lib_SCbase' => PATH_t3lib . 'class.t3lib_scbase.php',
	'tx_dam_db' => t3lib_extMgm::extPath('dam') . 'lib/class.tx_dam_db.php',
);
?>